# No theme applied — disables Jekyll layout
# Minimal setup for raw HTML/Markdown rendering

title: Balkar’s Clean Site
description: Experiments, insights, and structured notes — without any theme.
markdown: kramdown
